home/home/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('monitor/', include('monitor.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

home/monitor/urls.py
from django.urls import path

from . import views

app_name = "monitor"
urlpatterns = [
    path('', views.index, name='index'),
    path('node_list/', views.node_list, name='node_list'),
    path('node/<int:node_id>/', views.node_detail, name='node_detail'),
    path('node/update/<int:node_id>/', views.node_update, name='node_update'),
    path('node/remove/<int:node_ref>/', views.node_remove, name='node_remove'),
]

home/monitor/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

# *******************************************************************


class HassDomain(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name}"

# *******************************************************************


class DeviceType(models.Model):
    name = models.CharField(max_length=30)
    descr = models.TextField(null=True, blank=True)
    noStatus = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering = ["name"]

# *******************************************************************


class Node(models.Model):
    nodeID = models.CharField(max_length=100)
    devType = models.ForeignKey(
        DeviceType, on_delete=models.SET_NULL, null=True, blank=True
    )
    descr = models.TextField(null=True, blank=True)
    topic = models.CharField(max_length=300, null=True, blank=True)
    status = models.CharField(
        max_length=1,
        default="X",
        help_text="'C' for current/online, 'X' for offline, 'M' for maintenance mode (no notifications)",
    )
    textStatus = models.CharField(max_length=30, null=True, blank=True)
    is_gateway = models.BooleanField(default=False)
    notification_sent = models.BooleanField(default=False)
    lastseen = models.DateTimeField(null=True, blank=True)
    status_sent = models.DateTimeField(null=True, blank=True)
    next_update = models.DateTimeField(null=True, blank=True)
    lastData = models.TextField(null=True, blank=True)
    allowedDowntime = models.IntegerField(
        default=60,
        help_text="Minutes that the node can be 'unheard' before being marked as Offline",
    )
    battPower = models.BooleanField(default=False, help_text="True if the node is battery powered")
    battName = models.CharField(
        max_length=30,
        null=True,
        blank=True,
        help_text="Name of JSON attribute that contains battery level",
    )
    battLevel = models.FloatField(default=0.0)
    battVoltage = models.FloatField(default=0.0)
    battMonitor = models.BooleanField(default=False)
    battWarn = models.FloatField(
        default=0.0, help_text="Battery level at which to send warning messages"
    )
    battCritical = models.FloatField(
        default=0.0, help_text="Battery level at which to send critical messages"
    )
    battStatus = models.CharField(
        max_length=1,
        default=" ",
        null=True, 
        blank=True,
        help_text="'G' for good, 'W' for warning, 'C' for critically low, ' ' for not monitored",
    )
    linkQuality = models.FloatField(
        default=0.0, help_text="The link quality of the node",null=True, 
        blank=True,
    )
    RSSI = models.FloatField(
        default=0.0, help_text="Received Signal Strength Indicator"
    )

    model = models.CharField(max_length=100, null=True, blank=True)
    macAddr = models.CharField(max_length=20, null=True, blank=True)
    ipAddr = models.CharField(max_length=20, null=True, blank=True)
    generated = models.CharField(max_length=30, null=True, blank=True)
    lstMQTTTopic = models.CharField(max_length=100, null=True, blank=True)
    storeMQTT = models.BooleanField(default=False)
    
    class Meta:
        ordering = ["nodeID"]

    def __str__(self):
        return self.nodeID

    def online(self, msg):
        self.status = 'C'
        self.textStatus = "Online"
        self.lastseen = timezone.now()
        self.lstMQTTTopic = msg.topic
        self.save()
        return


class Entity(models.Model):
    entityID = models.CharField(max_length=100)
    node = models.ForeignKey(Node, on_delete=models.CASCADE)
    domain = models.ForeignKey(
        HassDomain, on_delete=models.SET_NULL, null=True, blank=True
    )
    state_topic = models.CharField(max_length=200, null=True, blank=True)
    json_key = models.CharField(max_length=50, null=True, blank=True)
    availability_topic = models.CharField(
        max_length=200, null=True, blank=True)
    text_state = models.CharField(max_length=200, null=True, blank=True)
    num_state = models.FloatField(default=0.0)

    def __str__(self):
        return(f"Node: {self.node.nodeID}, Entity: {self.entityID}")



class Setting(models.Model):
    sKey = models.CharField(max_length=30)
    sValue = models.CharField(max_length=300, default=" ")
    dValue = models.DateTimeField(default=timezone.now)
    fValue = models.FloatField(default=0)

    def __str__(self):
        return "{}: {}".format(self.sKey, self.sValue)

class MqttStore(models.Model):
    """
    Stores all mqtt messages
    """

    node = models.ForeignKey(
        Node, null=True, on_delete=models.SET_NULL, related_name="mqsNode"
    )
    received = models.DateTimeField(auto_now=True)
    topic = models.CharField(max_length=100)
    payload = models.TextField()
    qos = models.IntegerField()
    retained = models.BooleanField()

    class Meta:
        verbose_name = "MqttStore"
        ordering = ["-received"]

    def __str__(self):
        return f"mqtt: {self.node.nodeID}, topic: {self.topic}, payload: {self.payload}, received: {self.received}, retained: {self.retained}"

home/monitor/forms.py
from django import forms
from .models import Node

#class NodeUpdateForm(forms.Form):
#    descr = forms.CharField(label='Node description', widget=forms.Textarea)

class NodeUpdateModelForm(forms.ModelForm):
    class Meta:
        model = Node
        fields = (['descr', 'topic', 'status', 'allowedDowntime', 'battName', 'battWarn', 'battCritical'])
        widgets = {
            'descr': forms.Textarea(attrs={'rows': 3}),
        }

home/monitor/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth.models import User
from django.views import generic
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Node

from .forms import NodeUpdateModelForm

# Create your views here.
# *****************************************************************************
def node_list(request):
    """ ."""
    node_list = Node.objects.all()
    context = {
        "node_list": node_list,
    }
    return render(request, "monitor/node_list.html", context)

# *****************************************************************************
def index(request):
    nodeList = Node.objects.order_by("nodeID")
    currentList = nodeList.exclude(status__iexact = "M")

    context = {
        "nodeList": currentList,
    }
    return render(request, "monitor/index.html", context)


# *****************************************************************************
def node_detail(request, node_id):
    node = Node.objects.get(pk=node_id)
    try:
        newStatus = request.POST["newStatus"]
        node.textStatus = newStatus
        node.save()
    except Exception as e:
        print(e)
    context = {
        "node": node,
    }
    return render(request, "monitor/node_detail.html", context)


# *****************************************************************************
@login_required
def node_update(request, node_id):
    # print("Enter node_update")
    # print(request.POST)
    node = get_object_or_404(Node, pk=node_id)

    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = NodeUpdateModelForm(request.POST, instance=node)
        # form = NodeUpdateForm(request.POST)
        # print("Post received")
        # check whether it's valid:
        if form.is_valid():
            # print("Form valid")
            # process the data in form.cleaned_data as required
            form.save()
            # redirect to a new URL:
            return HttpResponseRedirect(reverse("monitor:node_detail", args=[node.id]))
    # if a GET (or any other method) we'll create a blank form
    else:
        form = NodeUpdateModelForm(instance=node)

    context = {"form": form, "node": node}
    return render(request, "monitor/node_update.html", context)

# *****************************************************************************
@login_required
def node_remove(request, node_ref):
    node = get_object_or_404(Node, pk=node_ref)
    if request.method == "POST":
        removeMe = "N"
        try:
            removeMe = request.POST["remove"]
        except:
            return HttpResponseRedirect(reverse("monitor:node_detail", args=[node.id]))
        if removeMe == "Y":
            node.status = "M"
            node.save()
            return HttpResponseRedirect(reverse("monitor:index"))
    context = {"node": node}

    return render(request, "monitor/node_remove.html", context)

home/monitor/templates/monitor/email-down.html
{% extends "monitor/email-base.html" %}

{% block title %}
Node down notification
{% endblock %}

{% block email-body %}
  <p>Hi Jim</p>

  <p>This is a notification to let you know that <span class="nodename">{{node.nodeID}}</span> is down.
  {% if node.descr %}
     <br><span class="descr">{{ node.descr }}</span>
  {% endif %}
  </p>
  <p>This is the information currently held for <b>{{ node.nodeID }}</b></p>
  <table class = "node-details">
    <tr>

      <td class = "node-details">Node ID:</td><td class = "nodename">{{ node.nodeID }}</td>
    </tr>
    <tr>
      <td class = "node-details">Current status:</td><td class = "node-details"> {{ node.textStatus }}</td>
    </tr>
    
    <tr>
      <td class = "node-details">Minutes allowed to be silent:</td><td class = "node-details">{{ node.allowedDowntime }}</td>
    </tr>
    <tr>
      <td class = "node-details">Last seen at:</td><td class = "node-details">{{ node.lastseen }}</td>
    </tr>
    <tr>
      <td class = "node-details">Last notification sent at:</td><td class = "node-details">{{ node.status_sent }}</td>
    </tr>
    {% if node.battName %}
      <tr>
        <td class = "node-details">Last battery level:</td>
        {% if node.battLevel > node.battWarn %}
          <td class = "battNormal"> {{ node.battLevel }}</td>
        {% elif node.battLevel > node.battCritical %}
          <td class = "battWarning"> {{ node.battLevel }}</td>
        {% else %}
          <td class = "battCritical"> {{ node.battLevel }}</td>
        {% endif %}
      </tr>
      <tr>
        <td class = "node-details">Warn when battery is below:</td><td class = "node-details"> {{ node.battWarn }}</td>
      </tr>
      <tr>
        <td class = "node-details">Critical battery level:</td><td class = "node-details"> {{ node.battCritical }}</td>
      </tr>
    {% else %}
      <p>No battery data</p>
    {% endif %}
  </table>
  <div class="mqtt_instructions">
    <p>If node <span class="nodename"><a href="{{base_url}}{% url 'node_detail' node.id %}">{{node.nodeID}}</a></span> is permamently down you can remove it from the system. </p>
  </div>
{% endblock %}

home/monitor/templates/monitor/email-full.html
{% extends "monitor/email-base.html" %}

{% block title %}
Node down notification
{% endblock %}

{% block email-body %}
  <p>Hi Jim</p>

  <div id="devices">

    <div id="critical" class="devices">  
      {% if nodeCrit %}
        <p>Nodes that are critically low in battery levels are:</p>
        <ul id = "nodeCritUL">
        {% for entry in nodeCrit %}
          <li><span class="battCritical"><a href="{{base_url}}{% url 'node_detail' entry.id %}">{{entry.nodeID}}</a></span> <span class="lastseen">(Battery level {{entry.battLevel}})</span>
            {% if entry.descr %}
              <br><span class="descr">{{ entry.descr }}</span>
            {% endif %}
          </li>
        {% endfor %}
        </ul>
      {% endif %}
    </div>
        
    <div id="warning" class="devices">  
      {% if nodeWarn %}
        <p>Nodes that have low battery levels are:</p>
        <ul id = "nodeWarnUL">
        {% for entry in nodeWarn %}
          <li><span class="battWarning"><a href="{{base_url}}{% url 'node_detail' entry.id %}">{{entry.nodeID}}</a></span> <span class="lastseen">(Battery level {{entry.battLevel}})</span>
            {% if entry.descr %}
              <br><span class="descr">{{ entry.descr }}</span>
            {% endif %}
          </li>
        {% endfor %}
        </ul>
      {% endif %}
    </div>

    <div id="nodeDown" class="devices">  
        {% if nodeDown %}
        <p>Nodes that are DOWN are:</p>
        <ul id = "nodeDown">
        {% for entry in nodeDown %}
          <li><span class="node_down"><a href="{{base_url}}{% url 'node_detail' entry.id %}"">{{entry.nodeID}}</a></span> <span class="lastseen">(last seen {{entry.lastseen}})</span>
            {% if entry.descr %}
              <br><span class="descr">{{ entry.descr }}</span>
            {% endif %}
          </li>
        {% endfor %}
        </ul>
        {% else %}
          <p class="nodeup">All nodes are operational.</p>
        {% endif %}
    </div>

    <div id="nodes" class="devices">  
      {% if nodes %}
        <p>Nodes that are fine are:</p>
        <ul id = "nodeOK">
        {% for entry in nodeOK %}
          <li><span class="nodeup"><a href="{{base_url}}{% url 'node_detail' entry.id %}">{{entry.nodeID}}</a></span> <span class="lastseen">(last seen {{entry.lastseen}})</span>
            {% if entry.descr %}
              <br><span class="descr">{{ entry.descr }}</span>
            {% endif %}
          </li>
        {% endfor %}
        </ul>
        {% else %}
          <p class="nodeup">All nodes are operational.</p>
        {% endif %}
    </div>



  </div>  

{% endblock %}
    

home/monitor/templates/monitor/email-info.html
{% extends "monitor/email-base.html" %}

{% block title %}
MQTT Request
{% endblock %}

{% block email-body %}
  <p>Hi <b>{{ name }}</b></p>

  <p>monitor received a request to provide system information. 
  </p>
  
  <p>This is the information currently held for <b>{{ node.nodeID }}</b></p>
    <table>
      <tr>
        <td>Node ID:</td><td>{{ node.nodeID }}</td>
      </tr>
      <tr>
        <td>Current status:</td><td> {{ node.textStatus }}</td>
      </tr>
      
      <tr>
        <td>Specific node topic:</td><td>{{ node.topic }}</td>
      </tr>
      <tr>
        <td>Last seen at:</td><td>{{ node.lastseen }}</td>
      </tr>
      <tr>
        <td>Is this a Gateway?:</td><td> {{ node.is_gateway }}</td>
      </tr>

    </table>
  
{% endblock %}

home/monitor/templates/monitor/index.html
{% extends "monitor/webbase.html" %}

{% block pagerefresh %}<meta http-equiv="refresh" content="30">{% endblock %}

{% block title %}
Node List
{% endblock %}

{% block web-body %}
  <h1>Node List</h1>
  <div id="devices">
    <div class = "row row-cols-6">
      {% for node in nodeList %}
        <div class="col-md-2 mb-md-2">
          {% if node.status == 'X' %} 
            <div class="card bg-dark text-white">
          {% elif node.status == 'M' %} 
            <div class="card bg-warning">
          {% else %}
            <div class="card bg-success">
          {% endif %}
            <div class="card-header">
              {% if node.status == 'X' %}
                <a href="{% url 'monitor:node_detail' node.id %}" class="stretched-link text-white">{{node.nodeID}}</a>
              {% else %}
                <a href="{% url 'monitor:node_detail' node.id %}" class="stretched-link text-body">{{node.nodeID}}</a>
              {% endif %}
            </div>
            
            <div class="card-body">
              {% if node.descr %} {{node.descr }} <br> {% endif %}
              {% if node.battLevel %}Current battery value: {{node.battLevel}}<br>{% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

home/monitor/templates/monitor/node_detail.html
{% extends "monitor/webbase.html" %}

{% block title %}
Node Details
{% endblock %}

{% block web-body %}
  <div id="logged_on_user">
    Logged in as {{ user.username }}
  </div>
  <div id="node-header"><h2>Information currently held for <b>{{ node.nodeID }}</b></h2></div>
    <table>
      <tr><th>Node ID:</th>                   <th>{{ node.nodeID }}</th></tr>
      <tr><td>Description:</td>               <td>{{ node.descr }}</td></tr>
      <tr><td>Current status:</td>            <td>{{ node.textStatus }}</td></tr>
      <tr><td>Specific node topic:</td>       <td>{{ node.topic }}</td></tr>
      <tr><td>Last seen at:</td>              <td>{{ node.lastseen }}</td></tr>
      <tr><td>Last data:</td>                 <td>{{ node.lastData }}</td></tr>
      <tr><td>Minutes down time allowed:</td> <td>{{ node.allowedDowntime }}</td></tr>
      <tr><td>Signal strength:</td>           <td>{{ node.RSSI }}</td></tr>
      {% if node.battName %}
        <tr><th>Battery details:</th></tr>
        <tr><td>Battery name:</td>            <td>{{ node.battName }}</td></tr>
        <tr><td>Last battery level:</td>      <td>{{ node.battLevel }}</td></tr>
        <tr><td>Warning battery level:</td>   <td>{{ node.battWarn }}</td></tr>
        <tr><td>Critical battery level:</td>  <td>{{ node.battCritical }}</td></tr>
      {% endif %}
      {% if node.status == 'X' %}
        <div id="node_det_button" class="action_button">
          <a href="{% url 'monitor:node_remove' node.id %}" class="btn btn-danger" role="button">Remove</a>
        </div>
      {% endif %}
    </table>
    {% if node.entity_set.all %}
      <table>
        <tr>
          <th>Name</th>
          <th>Domain</th>
          <th>State</th>
        </tr>
        {% for e in node.entity_set.all %}
          <tr>
            <td>{{ e.json_key }}</td>
            <td>{{ e.domain.name }}</td>
            {% if e.text_state %}
              <td>{{ e.text_state }}</td>
            {% else %}
              <td>{{ e.num_state }}</td>
            {% endif %}
          </tr>
        {% endfor %}
      </table>
    {% endif %}
  <a href="{% url 'monitor:node_update' node.id %}" class="btn btn-info" role="button">Update details</a>
  <button onclick="window.location.href = '{% url 'monitor:index' %}';">Main menu</button>

{% endblock %}

home/monitor/templates/monitor/node_remove.html
{% extends "monitor/webbase.html" %}

{% block title %}
Node Details
{% endblock %}

{% block web-body %}

<div id="node-header"><h3>Remove Node</h3></div>
  <form action="{% url 'monitor:node_remove' node.id %}" method="POST">
    {% csrf_token %}  
    <table>
      <tr><th>NodeID: </th><th>{{ node.nodeID }}</th></tr>
      <tr><td>Description: </td><td>{{ node.descr }}</td></tr>
    </table>
    <div>
      By selecting 'Remove' this node will disappear from the main menu and no notifications will be sent out<br>
      If any messages are later received for this node it will return to an 'online' state<br>
      If nothing has been heard for a month, it will be permamently deleted.
    </div>
    <input name="remove" value="Y" type="hidden">
    <input type="submit" value="Remove">
    <span id="node_cancel_button" class="cancel_button">
      <a href="{% url 'monitor:node_detail' node.id %}" class="btn btn-link btn-outline-warning" role="button">Cancel</a>
    </span>
  </form>
  <a href="{% url 'monitor:index' %}" class="btn btn-info" role="button">Home</a>
</div>
{% endblock %}

home/monitor/templates/monitor/node_update.html
{% extends "monitor/webbase.html" %}

{% block title %}
Node Update
{% endblock %}

{% block web-body %}
  <div id="logged_on_user">
    Logged in as {{ user.username }}
  </div>
  <div id="node_update_form">
    <p>Editing information for <b>{{ node.nodeID }}</b></p>
    <form action="{% url 'monitor:node_update' node.id %}" method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
     <input type="submit" value="Update">
    </form>
  </div>
{% endblock %}

home/monitor/templates/monitor/webbase.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="{% static 'monitor/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    {% block pagerefresh %}<meta http-equiv="refresh" content="60">{% endblock %}
    <title>
	    {% block title %}
        Node monitoring system
      {% endblock %}
    </title>
  </head>
  <body>
    <div class="container-fluid">
    {% block web-body %}
      Node monitor
    {% endblock %}
    <!-- START FOOTER -->
    <div class="footer">
      <table class="footer">
        <tr>
          <td class="content-block">
            <span class="apple-link">Jim's monitoring system</span>
          </td>
        </tr>
      </table>
    </div>
    <!-- END FOOTER -->
  </div>
  </body>
</html>